### ISSUE TITLE
Problem after pull #102

### ISSUE THREAD

**Issue by cblims** [theolind/pymysensors#109]
Hi, got some problems after upgrading to latest home-assistant. As you notified some will experience this as a breaking change, and I do... The following exceptions are thrown on data from my power meter node:

```
 Invalid values: {24: '2144750550', 17: '2282', 18: '214475.0625'}: sensor platform: node 12 child 1: S_POWER requires value_type V_VAR @ data[54]
 Invalid values: {24: '2144750550', 17: '2282', 18: '214475.0625'}: sensor platform: node 12 child 1: S_POWER requires value_type V_VA @ data[55]
 Invalid values: {24: '2144750550', 17: '2282', 18: '214475.0625'}: sensor platform: node 12 child 1: S_POWER requires value_type V_POWER_FACTOR @ data[56]
```
As I read your code, and my logs, you require all possible metrics on S_POWER as mandatory, and that doesn't make sense to me. Is this check intentional, or am I doing something wrong in mysensors? VAR, VA and WATT are three different ways to describe power, you can have one without the other.

**Comment by MartinHjelmare** [comment]
Hi! If these are debug log messages, which I think they are, they by themselves don't mean that something is wrong. They are not exceptions. No, all possible value types per child type are not required for all platforms. Required value types depends on the platform. I've tried to explain this in the docs:
https://home-assistant.io/components/mysensors/#message-validation

I'm going to work on clarifying the logging. It might be more confusing than helpful in its current form.

What's the actual problem your're experiencing apart from seeing these debug messages in the log?

*For anyone else reading this, the log in the OP comes from [home assistant](https://github.com/home-assistant/home-assistant).*

**Comment by cblims** [comment]
Reason for asking is that my power meter worked perfectly before upgrade. No new input has been received after upgrade. So when seeing that there has been modifications that could break, and with my logs, I jumped to this conclusion.

So currently I don't see any but "Gateway startup complete", no values are appearing as before. I'm running nrf24L01 directly on my PI, and using mysgw to interface HA. A telnet connection to the socket gives me expected sensor outputs every 20s:
```
0;255;3;0;14;Gateway startup complete.
0;255;0;0;18;2.1.0
12;1;1;0;24;2145011229
12;1;1;0;17;1361
12;1;1;0;24;2145011305
12;1;1;0;17;1366
12;1;1;0;24;2145011381

Any suggestion where to look next?

```

**Comment by MartinHjelmare** [comment]
Value type 24 ie V_VAR1 is supposed to go along with S_CUSTOM not S_POWER. Do you want to report a custom value or do you want to report a V_VAR value, ie reactive power?

Value type 17, ie V_WATT, should work with S_POWER. Is that not showing? Can you record a debug log from home assistant after start of node 12 until it has sent at least one round of values?

**Comment by MartinHjelmare** [comment]
I see you're using the same child id for the different measurements. That's not really supported by home assistant. Only platforms that require multiple values should have children that collect multiple value types. Not following this used to lead to entity_ids changing between measurements. Could lead to worse things now? I haven't analyzed that in detail yet after the refactor.

**Comment by cblims** [comment]
I'm running code based on [pulse power example](https://www.mysensors.org/build/pulse_power). They use V_VAR1 to write current meter reading to the sensor.

**Comment by cblims** [comment]
Log dump(grep of mysensors):
```
2017-08-29 21:24:16 INFO (MainThread) [homeassistant.loader] Loaded sensor.mysensors from homeassistant.components.sensor.mysensors
2017-08-29 21:24:17 INFO (MainThread) [homeassistant.loader] Loaded mysensors from homeassistant.components.mysensors
2017-08-29 21:24:17 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mysensors
2017-08-29 21:24:25 INFO (MainThread) [homeassistant.setup] Setting up mysensors
2017-08-29 21:24:26 INFO (MainThread) [homeassistant.setup] Setup of domain mysensors took 0.6 seconds.
2017-08-29 21:24:26 INFO (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=mysensors>
2017-08-29 21:24:34 DEBUG (Thread-3) [homeassistant.components.mysensors] No child values for node 3 child 1
2017-08-29 21:24:34 DEBUG (Thread-3) [homeassistant.components.mysensors] No child values for node 11 child 1
2017-08-29 21:24:34 DEBUG (Thread-3) [homeassistant.components.mysensors] Invalid values: {24: '2144750550', 17: '2282', 18: '214475.0625'}: sensor platform: node 12 child 1: S_POWER requires value_type V_VAR @ data[54]
2017-08-29 21:24:34 DEBUG (Thread-3) [homeassistant.components.mysensors] Invalid values: {24: '2144750550', 17: '2282', 18: '214475.0625'}: sensor platform: node 12 child 1: S_POWER requires value_type V_VA @ data[55]
2017-08-29 21:24:34 DEBUG (Thread-3) [homeassistant.components.mysensors] Invalid values: {24: '2144750550', 17: '2282', 18: '214475.0625'}: sensor platform: node 12 child 1: S_POWER requires value_type V_POWER_FACTOR @ data[56]
2017-08-29 21:24:34 INFO (MainThread) [homeassistant.core] Bus:Handling <Event platform_discovered[L]: platform=mysensors, service=load_platform.sensor, discovered=devices=[(1835100784, 12, 1, 17), (1835100784, 12, 1, 18)], name=mysensors>
2017-08-29 21:24:34 INFO (Thread-13) [mysensors.gateway_tcp] Trying to connect to ('127.0.0.1', 5003)
2017-08-29 21:24:34 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mysensors
2017-08-29 21:24:34 INFO (Thread-4) [homeassistant.components.mysensors] Adding new devices: [<Entity Energy Meter 12 1: None>, <Entity Energy Meter 12 1: None>]
2017-08-29 21:24:34 INFO (Thread-13) [mysensors.gateway_tcp] Connected to ('127.0.0.1', 5003)
2017-08-29 21:24:34 DEBUG (Thread-8) [homeassistant.components.mysensors] Entity update: Energy Meter 12 1: value_type 24, value = 2144750550
2017-08-29 21:24:34 DEBUG (Thread-9) [homeassistant.components.mysensors] Entity update: Energy Meter 12 1: value_type 24, value = 2144750550
2017-08-29 21:24:34 DEBUG (Thread-8) [homeassistant.components.mysensors] Entity update: Energy Meter 12 1: value_type 17, value = 2282
2017-08-29 21:24:34 DEBUG (Thread-9) [homeassistant.components.mysensors] Entity update: Energy Meter 12 1: value_type 17, value = 2282
2017-08-29 21:24:34 DEBUG (Thread-8) [homeassistant.components.mysensors] Entity update: Energy Meter 12 1: value_type 18, value = 214475.0625
2017-08-29 21:24:34 DEBUG (Thread-9) [homeassistant.components.mysensors] Entity update: Energy Meter 12 1: value_type 18, value = 214475.0625
2017-08-29 21:24:34 INFO (Thread-13) [mysensors] n:0 c:255 t:3 s:14 p:Gateway startup complete.

```

**Comment by cblims** [comment]
According to mysensors api, all devices should accept V_VAR[1-5]

Type | Value | Comment | Used by
-- | -- | -- | --
V_VAR1 | 24 | Custom value | Any device
V_VAR2 | 25 | Custom value | Any device
V_VAR3 | 26 | Custom value | Any device
V_VAR4 | 27 | Custom value | Any device
V_VAR5 | 28 | Custom value | Any device

**Comment by MartinHjelmare** [comment]
Yeah, I've seen that. I've been thinking about allowing that. You should still use different child ids for different measurements though.

**Comment by cblims** [comment]
hmm, they are kind of the same measurement. V_VAR1 and V_KWH is more or less the same value. V_VAR1 is used to update the sensor on reboot. If you look into the example code at mysensors, can you please advice how to do this in a better way? Not sure if different child id are best way.

I think its best to let pymysensors be compliant with the examples at mysensors.org, and not require too much rewrite of source code to make the sensor work. Of course, some of the examples are pretty old and not compliant with 2.0.

**Comment by MartinHjelmare** [comment]
Regarding same/different child ids for different measurements, that's not related to pymysensors, but to home assistant. It's got to do with how we generate entity_ids and how home assistant in general works.

Each entity should only have one main state value, eg a sensor measurement. An entity can have multiple supplemental state attributes on top of that but only ever one state at the same time. Since each of the sensor measurements maps to a main state in home assistant, each sensor measurement should create a new entity. Each entity requires a unique entity_id. For a long time the mysensors entity_id structure in home assistant has been [sketchname]_[node_id]_[child_id].

So currently without changing the entity_id structure it's not good to have the same child id for different measurements, if you want to avoid problems with changing entity_ids.

Also the base concept of the mysensors implementation in home assistant is built around 1 child is 1 entity per platform.

There's no limiting reason that I can see in the pulse meter example sketch that would hinder you from using different child ids for the different measurements.

**Comment by MartinHjelmare** [comment]
Except from the issue with value type 24 and the issue with same child id, your log looks ok. The mysensors component tries to add two entities to the sensor platform. Are none of these entities added to home assistant?

**Comment by MartinHjelmare** [comment]
If you don't see any more debug logging from the mysensors package after the "Gateway startup complete" message, I think that the pymysensors gateway thread might have crashed. You might not get a stack trace until you shut down home assistant due to the async nature of home assistant. The problem could be the same as described here: https://community.home-assistant.io/t/problem-with-mysensors-mqtt-client-gateway-in-0-52/25623

There's a fix in place for this bug planned to go out in 0.52.2.

You could check your persistence file for `null` value for the protocol_version for any sensor.

**Comment by cblims** [comment]
This explains why I have multiple entities in HA. You suggestion implies three different children, one S_POWER for W, one S_POWER for KWH, and last one S_CUSTOM for V_VAR1. Current implementation require the sensor to present at least one value to be discovered by HA. Is this per child or per node? The tricky thing for power meter is that it requires a value set in V_VAR1 to start counting KWH. Today I make the node known by sending W without waiting for V_VAR1. Will this still work when implementing three children?

Current listing in HA:
Entity | State | Attributes
-- | -- | --
sensor.energy_meter_12_1 | 1346 | V_KWH: 214531.0156 icon: mdi:power-plug unit_of_measurement: W device: 127.0.0.1 battery_level: 0 custom_ui_state_card: custom_powermeter friendly_name: Strømmåler V_WATT: 1346 sensor_class: power node_id: 12 V_VAR1: 2145310121 description:  child_id: 1
sensor.energy_meter_12_1_2 | 214531.0156 | V_KWH: 214531.0156 hidden: true friendly_name: Energy Meter 12 1 unit_of_measurement: kWh V_VAR1: 2145310121 V_WATT: 1346 node_id: 12 child_id: 1 description:  device: 127.0.0.1 battery_level: 0

I'll try to shutdown HA, and see if anything appears in the log...

**Comment by MartinHjelmare** [comment]
Each child need a value to get added to home assistant. The children that don't send an initial value and are not loaded by persistence will not show in home assistant until they send a value. I don't think this will change the behavior of your sensor. You could edit the JSOn persistence file and transfer the old pulse count from the previous single child to the new child in the file to make sure that the third child starts reporting kWh at once.

**Comment by cblims** [comment]
Indeed the protocol version was set to null. I removed the parameter, and after restart its updated to 1.4. Now I get lots of these in the log, HA is not updated. (node is still running same software)

```
2017-08-31 09:53:14 DEBUG (Thread-13) [homeassistant.components.mysensors] Node update: node 12 child 1
2017-08-31 09:53:14 DEBUG (Thread-13) [homeassistant.components.mysensors] Invalid values: {24: '2145635005', 17: '1258', 18: '214563.5000'}: sensor platform: node 12 child 1: S_POWER requires value_type V_VAR @ data[54]
2017-08-31 09:53:14 DEBUG (Thread-13) [homeassistant.components.mysensors] Invalid values: {24: '2145635005', 17: '1258', 18: '214563.5000'}: sensor platform: node 12 child 1: S_POWER requires value_type V_VA @ data[55]
2017-08-31 09:53:14 DEBUG (Thread-13) [homeassistant.components.mysensors] Invalid values: {24: '2145635005', 17: '1258', 18: '214563.5000'}: sensor platform: node 12 child 1: S_POWER requires value_type V_POWER_FACTOR @ data[56]
2017-08-31 09:53:14 ERROR (Thread-13) [mysensors] pop index out of range
Traceback (most recent call last):
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/mysensors/__init__.py", line 308, in alert
    self.event_callback(msg)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/mysensors.py", line 479, in mysensors_callback
    dev_ids.pop(idx)
IndexError: pop index out of range
```

**Comment by MartinHjelmare** [comment]
It's not obvious what case could lead to that error. Can you post or share your persistence file?

**Comment by cblims** [comment]
{"0": {"sketch_name": null, "type": 18, "sketch_version": null, "sensor_id": 0, "_battery_level": 0, "children": {}, "protocol_version": "2.1.0"}, "11": {"sketch_name": "Energy Meter", "type": 17, "sketch_version": "1.0", "sensor_id": 11, "_battery_level": 0, "children": {"1": {"values": {}, "type": 13, "id": 1, "description": ""}}, "protocol_version": "1.4.1"}, "3": {"sketch_name": "Water Meter", "type": 17, "sketch_version": "1.2", "sensor_id": 3, "_battery_level": 0, "children": {"1": {"values": {}, "type": 21, "id": 1, "description": "1.4.1"}}, "protocol_version": "1.4.1"}, "12": {"sketch_name": "Energy Meter", "type": null, "sketch_version": "1.0", "sensor_id": 12, "_battery_level": 0, "children": {"1": {"values": {"24": "2145739640", "17": "818", "18": "214573.9688"}, "type": 13, "id": 1, "description": ""}}, "protocol_version": "1.4"}}

**Comment by MartinHjelmare** [comment]
Thanks, I've figured it out. I'll fix that bug. It slipped through testing cause I didn't test the case with more than one entity per platform per child. If you change your sketch to have 1 measurement per child, you will also avoid the bug.

**Comment by MartinHjelmare** [comment]
Fix has been merged and released in home assistant.
