### ISSUE TITLE
Parse error on gateway startup

### ISSUE THREAD

**Issue by davidedmundson** [theolind/pymysensors#17]
I'm running MySensors 1.5, and I'm pretty sure I have debug turned off in MyConfig.h

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/admin/.homeassistant/lib/mysensors/mysensors.py", line 312, in run
    response = self.handle_queue()
  File "/home/admin/.homeassistant/lib/mysensors/mysensors.py", line 222, in handle_queue
    reply = func(*args, **kwargs)
  File "/home/admin/.homeassistant/lib/mysensors/mysensors.py", line 105, in logic
    msg = Message(data)
  File "/home/admin/.homeassistant/lib/mysensors/mysensors.py", line 397, in __init__
    self.decode(data)
  File "/home/admin/.homeassistant/lib/mysensors/mysensors.py", line 417, in decode
    self.sub_type) = [int(f) for f in data]
  File "/home/admin/.homeassistant/lib/mysensors/mysensors.py", line 417, in <listcomp>
    self.sub_type) = [int(f) for f in data]
ValueError: invalid literal for int() with base 10: 'Gateway startup compl0'

**Comment by MartinHjelmare** [comment]
This can happen if partial data is received from the serial gateway. The error is handled after the fix in  https://github.com/theolind/pymysensors/pull/15. This fix should probably make it into the next release of home assistant.

'll add another fix soon which I hope will make the situation occur less frequently at startup.

Right now the program is sleeping 3 s after connecting to the serial gateway to give the arduino time to reset. I've done more testing on this, and I can't see any benefit of the wait, so I'll remove that again. I added the wait to possibly reduce another error where bad bytes were received, possibly due to the program reading before the arduino was ready.

**Comment by MartinHjelmare** [comment]
This should be fixed as of https://github.com/balloob/home-assistant/pull/1223.
