### ISSUE TITLE
Error on loading of sensors JSON after inpropper shutdown

### ISSUE THREAD

**Issue by oeysteinhansen** [theolind/pymysensors#40]
### Issue description:
Stack trace from startup of Home-Assistant 0.16

```
ERROR:homeassistant.bootstrap:Error during setup of component mysensors
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/bootstrap.py", line 105, in _setup_component
    if not component.setup(hass, config):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/mysensors.py", line 111, in setup
    port, persistence, persistence_file, version, baud_rate)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/mysensors.py", line 75, in setup_gateway
    baud=baud_rate)
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 280, in __init__
    persistence_file, protocol_version)
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 32, in __init__
    self._load_sensors()
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 165, in _load_sensors
    self._perform_file_action(self.persistence_file, 'load')
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 180, in _perform_file_action
    func(filename)
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 148, in _load_json
    self.sensors = json.load(file_handle, cls=MySensorsJSONDecoder)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 331, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

This happened after an improper shutdown of Home Assistant / pymysensors. (A terminal window running 'hass' was closed.) 

The issue is probably that the sensors JSON file is updated / over written on each sensor update, and there are no fall-back if the file is not completed before a shutdown / or power loss.

Reproduce by replacing the sensor JSON file with an empty file.

### Workaround
Remove the JSON file from the filesystem, and let mysensors populate it again.

### Possible fix
When writing the JSON file. Do this in a tree step process. 
1. Move the current JSON file to a temporary filename. (mysensors.json => mysensors.json_old)
2. Write the sensor JSON file to disk, as previous.
3. Remove the temporary JSON file.

When reading the JSON file. Do this process.
1. Read sensor JSON file if present.
2. If this fails Copy the temporary JSON file to the sensor JSON file name.
3. Read sensor JSON file if present.
4. If this fails revert to an empty JSON file, and set an error message in the log.
5. Always delete the temporary JSON file if present.

**Comment by MartinHjelmare** [comment]
Thanks for the report and suggestions. Can you test #41 and see if that solves this?

**Comment by MartinHjelmare** [comment]
#41 is merged.
